name: 'Run IronPython'
description: 'A GitHub Action that runs a Python script with a Hello, World! program.'
author: 'Your Name'
branding:
  icon: "package"
  color: "purple"

inputs:
  source:
    description: "Source folder"
    required: true
  package-name:
    description: "Name of the package."
    required: true
  version:
    description: "Version tag of the plugin"
    required: true
  type:
    default: "ghpy"
    description: "Extension type of the package. Defaults to \".ghpy\""
    required: false
outputs:
  build_path:
    description: "Location of the built package."
    value: ${{steps.compile.outputs.build_path}}
    
runs:
  using: 'composite'
  steps:
    - name: Compile Plugin
      id: compile
      shell: pwsh
      run: ipy ${{github.action_path}}/main.py ${{inputs.source}} ${{inputs.package-name}} ${{inputs.version}} ${{inputs.type}}
