name: 'Run IronPython'
description: 'A GitHub Action that runs a Python script with a Hello, World! program.'
author: 'Your Name'
branding:
  icon: "package"
  color: "purple"

inputs:
  source:
    description: "Source folder"
    required: false
  package-name:
    description: "Name of the package."
    required: false
outputs:
  build_path:
    description: "Location of the built package."
runs:
  using: 'composite'
  steps:

    - name: Install IronPython v2.7.12
      shell: pwsh
      run: choco install ironpython --version=2.7.12

    - name: Message
      shell: pwsh
      run: |
        "The Message is: ${{ inputs.source }}"
        "The Name is: ${{ inputs.package-name }}"

    - name: Run Script
      shell: bash
      run: ipy client.py ${{inputs.source}} ${{inputs.package-name}}
