name: "Make-GhPy"
description: "About
GitHub Action to compile IronPython files into Grasshopper-Python (GhPy) plugin."
author: "Kaushik LS"
branding:
  icon: "chevron-right"
  color: "yellow"

inputs:
  source:
    description: "Source folder"
    required: true
  
  package-name:
    description: "Name of the package."
    required: true
  
  version:
    description: "Version tag of the plugin"
    required: true
  
  type:
    default: "ghpy"
    description: "Extension type of the package. Defaults to \".ghpy\""
    required: false
  
  ironpython:
    default: false
    description: "If true, install IronPython v2.7.12"
    required: false

outputs:
  build:
    description: "Location of the built package."
    value: ${{steps.compile.outputs.build}}
    
runs:
  using: 'composite'
  steps:

    - name: Install IronPython
      shell: pwsh
      if: ${{inputs.ironpython == 'true'}}
      run: choco install ironpython --version=2.7.12

    - name: Compile Plugin
      id: compile
      shell: pwsh
      run: ipy ${{github.action_path}}/build.py ${{inputs.source}} ${{inputs.package-name}} ${{inputs.version}} ${{inputs.type}}
