name: "Make-GhPy"
description: "GitHub Action to compile IronPython files into Grasshopper-Python (GhPy) plugin."
author: "Kaushik LS"
branding:
  icon: "package"
  color: "gray-dark"

inputs:
  source:
    description: "Root folder for python source."
    required: true
  
  package-name:
    description: "Name of the compiled binary / plugin."
    required: true
  
  version:
    description: "Version tag to add with name."
    required: true
  
  type:
    default: "ghpy"
    description: "Extension type of the package. Defaults to \".ghpy\""
    required: false
  
  ironpython:
    default: false
    description: "If true, installs IronPython v2.7.12 internally."
    required: false

outputs:
  name:
    description: "Name of the compiled package."
    value: ${{ steps.compile.outputs.name }}
  
  full-name:
    description: "Full name of the compiled package."
    value: $${{ steps.compile.outputs.full-name }}
  
  build:
    description: "Location of the compiled package."
    value: ${{ steps.compile.outputs.build }}

runs:
  using: 'composite'
  steps:

    - name: Install IronPython
      shell: pwsh
      if: ${{ inputs.ironpython == 'true' }}
      run: choco install ironpython --version=2.7.12

    - name: Compile Plugin
      id: compile
      shell: pwsh
      run: ipy ${{ github.action_path }}/build.py ${{ inputs.source }} ${{ inputs.package-name }} ${{ inputs.version }} ${{ inputs.type }}
