name: Test make-ghpy action

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [windows-latest]

    steps:
    
    - name: Build Python Plugin
      uses: ./