name: Test Action

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install IronPython
      shell: pwsh
      run: choco install ironpython --version=2.7.12
    
    - name: Build Plugin
      id: build-plugin
      uses: ./
      with:
        source: tests
        package-name: plugin
        version: v0.0.1-alpha
        type: ghpy
        ironpython: false

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build-plugin.outputs.name }}
        path: ${{ steps.build-plugin.outputs.build }}
        if-no-files-found: error
        retention-days: 1
