name: Test make-ghpy action

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Build Python Plugin
      uses: ./
      with:
        source: src
        package-name: plugin.ghpy
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyPlugin.ghpy
        path: bin/plugin.ghpy
